call "%DevEnvDir%..\Tools\vsdevcmd.bat" -no_logo
set PostBuildTool="%SolutionDir%PostBuildTool\bin\x86\%Configuration%\net48\PostBuildTool"
set ServerName=ThMouseXServer
set ClientName=ThMouseX
set TypeLibName=ThMouseXServer.dll
set Architecture=*
set ServerPath="%ProjectDir%%OutDir%ThMouseXServer.dll"
set ServerManifestPath=server.manifest
set ClientManifestPath=client.manifest
set TlbPath=server.tlb
%PostBuildTool% GenerateComServerManifest %ServerName% %TypeLibName% %Architecture% %ServerPath% %ServerManifestPath%
   if %errorlevel% neq 0 exit /b %errorlevel%
%PostBuildTool% GenerateComServerManifest %ClientName% %TypeLibName% %Architecture% %ServerPath% %ClientManifestPath%
   if %errorlevel% neq 0 exit /b %errorlevel%
tlbexp /nologo /win32 %ServerPath% /out:%TlbPath%
   if %errorlevel% neq 0 exit /b %errorlevel%
%PostBuildTool% ImportResource %ServerPath% %TlbPath% typelib #1
   if %errorlevel% neq 0 exit /b %errorlevel%
if not exist AutoGenerated mkdir AutoGenerated
cd AutoGenerated
cl -nologo ../GenerateComHeaders.cpp
cd ..