#pragma comment(lib, "shlwapi.lib")
#pragma comment(lib, "psapi.lib" )
#pragma comment(lib, "delayimp")
#pragma comment(lib, "Lib/x86/d3d9.lib")
#pragma comment(lib, "Lib/x86/D3dx9.lib")
#pragma comment(lib, "Lib/x86/dinput8.lib")
#pragma comment(lib, "Lib/x86/dxguid.lib")